import { Inter, DM_Sans, DM_Serif_Display } from "next/font/google";
import "./globals.css";
import AuthProvider from "../provider/AuthProvider";
import ClientLayoutWrapper from "@/components/ClientLayoutWrapper/ClientLayoutWrapper";

const dmSans = DM_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

const dmSerifDisplay = DM_Serif_Display({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-dm-serif",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} ${dmSans.className} ${dmSerifDisplay.className}`}
      >
        <AuthProvider>
          <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
